version: '3.8'

networks:
    telegram-proxy:
        driver: overlay
        external: false
    net:
        driver: overlay
        attachable: true

volumes:
    telegram-proxy: {}

services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        environment:
            - TAG=
            - SECRET=
            - WORKERS=16
        volumes:
            - telegram-proxy:/data
        deploy:
            mode: replicated
            replicas: 1
        networks:
            - telegram-proxy
            - net
        ports:
            - 4444:443/tcp